repos:
-   repo: https://github.com/adamchainz/django-upgrade
    rev: "1.12.0"  # replace with latest tag on GitHub
    hooks:
    -   id: django-upgrade
        args: [--target-version, "4.1"]   # Replace with Django version
