# Generated by Django 3.0.6 on 2020-05-15 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Related User'),
        ),
        migrations.AddField(
            model_name='mtroutersmodel',
            name='filters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FiltersModel', verbose_name='Filters'),
        ),
        migrations.AddField(
            model_name='mtroutersmodel',
            name='httpconnectors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.HTTPccmModel', verbose_name='SMPP Connectors'),
        ),
        migrations.AddField(
            model_name='mtroutersmodel',
            name='smppconnectors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SMPPccmModel', verbose_name='SMPP Connectors'),
        ),
        migrations.AddField(
            model_name='moroutersmodel',
            name='filters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FiltersModel', verbose_name='Filters'),
        ),
        migrations.AddField(
            model_name='moroutersmodel',
            name='httpconnectors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.HTTPccmModel', verbose_name='SMPP Connectors'),
        ),
        migrations.AddField(
            model_name='moroutersmodel',
            name='smppconnectors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SMPPccmModel', verbose_name='SMPP Connectors'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
