# Generated by Django 3.0.14 on 2021-08-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200515_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgid', models.CharField(max_length=45, verbose_name='Message ID')),
                ('source_connector', models.CharField(max_length=15, verbose_name='Source Connector')),
                ('routed_cid', models.CharField(db_index=True, max_length=30, verbose_name='Routed CID')),
                ('source_addr', models.CharField(max_length=40, verbose_name='Source Address')),
                ('destination_addr', models.CharField(max_length=40, verbose_name='Destination Address')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Rate')),
                ('pdu_count', models.PositiveIntegerField(default=1, verbose_name='PDU Count')),
                ('short_message', models.BinaryField(verbose_name='Short Message')),
                ('binary_message', models.BinaryField(verbose_name='Binary Message')),
                ('status', models.CharField(db_index=True, max_length=15, verbose_name='Status')),
                ('uid', models.CharField(db_index=True, max_length=15, verbose_name='UID')),
                ('trials', models.PositiveIntegerField(default=1, verbose_name='Trials')),
                ('created_at', models.DateTimeField(db_index=True, verbose_name='Created At')),
                ('status_at', models.DateTimeField(verbose_name='Status At')),
            ],
            options={
                'verbose_name': 'Submit Log',
                'verbose_name_plural': 'Submit Logs',
                'db_table': 'submit_log',
                'ordering': ('-created_at',),
            },
        ),
    ]
