# Generated by Django 5.2.10 on 2026-01-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_submitlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitlog',
            name='charge',
            field=models.DecimalField(blank=True, decimal_places=7, default=0.0, max_digits=12, null=True, verbose_name='Charge'),
        ),
        migrations.AlterField(
            model_name='moroutersmodel',
            name='type',
            field=models.CharField(choices=[('DefaultRoute', 'DefaultRoute'), ('StaticMORoute', 'StaticMORoute'), ('RandomRoundrobinMORoute', 'RandomRoundrobinMORoute'), ('FailoverMORoute', 'FailoverMORoute')], max_length=24, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='mtroutersmodel',
            name='type',
            field=models.CharField(choices=[('DefaultRoute', 'DefaultRoute'), ('StaticMTRoute', 'StaticMTRoute'), ('RandomRoundrobinMTRoute', 'RandomRoundrobinMTRoute'), ('FailoverMTRoute', 'FailoverMTRoute')], max_length=24, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='submitlog',
            name='binary_message',
            field=models.BinaryField(blank=True, null=True, verbose_name='Binary Message'),
        ),
        migrations.AlterField(
            model_name='submitlog',
            name='msgid',
            field=models.CharField(max_length=45, unique=True, verbose_name='Message ID'),
        ),
        migrations.AlterField(
            model_name='submitlog',
            name='pdu_count',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='PDU Count'),
        ),
        migrations.AlterField(
            model_name='submitlog',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=7, default=0.0, max_digits=12, null=True, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='submitlog',
            name='routed_cid',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Routed CID'),
        ),
        migrations.AlterField(
            model_name='submitlog',
            name='short_message',
            field=models.BinaryField(blank=True, null=True, verbose_name='Short Message'),
        ),
        migrations.AlterField(
            model_name='submitlog',
            name='source_addr',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Source Address'),
        ),
        migrations.AlterField(
            model_name='submitlog',
            name='source_connector',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Source Connector'),
        ),
        migrations.AlterField(
            model_name='submitlog',
            name='trials',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Trials'),
        ),
    ]
